version: 2
jobs:
  build-dotnet:
    docker: 
      - image: microsoft/aspnetcore-build
    steps:
      - checkout
      - run: cd dotnet && dotnet build
      - run: cd dotnet && dotnet test

workflows:
  version: 2
  build-n-test:
    jobs:
      - build-dotnet